language: java
cache:
  directories:
  - "$HOME/.m2"
jdk:
- oraclejdk8
sudo: required
services:
- docker
notifications:
  email:
  - carnell28@gmail.com
  on_success: always
  on_failure: always
before_install:
- sudo curl -k -o /usr/local/bin/ecs-cli https://s3.amazonaws.com/amazon-ecs-cli/ecs-cli-linux-amd64-latest
- sudo chmod +x /usr/local/bin/ecs-cli
env:
  global:
  - secure: iGxwARigqu8cmngqlcIGD2f1wz+FnACnSzfn/mWPL1+YYh/tDBaoVVGR2S7mjjSkFfKHgBxId3HKv64RFbT/sxc/sdJW/5+Wq8PVWBPoNR38w3xS5CLLgv1wRNvcwoUti9if+K8dpdBHQ0Zs+KiiB7NB4a8PDIT0jTybLRvCC2fXgUqC6jL/qR3ZpmYAVULwOtzw557Ip95+fSQ8iGv9kK+C9m5NzBV1E2NTW3hsot1X42qVnG3xqphPOZpWOdC0UCxbofXWWmT3sf1fsKAlIRVBk9iWKI6XchHtm3rYbuya0qJROyLv6DNEflHX6r+iUjNkqaxTFhxOZZ847S3zybmOSu6annzG8gszuFw+YeaqfW6n+F9XkOFsLGbmy1+zDB7URTIKEf8+Ps1Pb6rYzzwrs5gT+Iul0+PgDLtilEkbDgUtZOEwyHfQsBAEqZDwDL9OHYos246wXGq3+4BgThmxWQ6btX4JInNGtE8PhLVLOH4S66/LMnvlqXYYAKYzNLWNAWllB4GaJYG5+wPcZ56ClHqsizEQxKgGTR2w08EP0J9Z21ThOxmnok2Z79Ck9uc485qy74Mo5mmC/+wn7Wm9TJSVwH+jvu2fJZ4+dSe0f1pkB9qu1+u/fdeolo5WqYY4swgWIfbaXyb62m9h1xjB/MA6VpIk4Qkp/h6LJI4=
  - secure: hd3JG0fjcudMVMSo3TqnOYQU7Gid4/c/wzXrsyHi4Y0gePyyDvI8MH/ph4hhtk31ChPRU78/D0L6/Dln+oaKIfJxxkzIZTzl/QEtVLU/z28g+kdpcbbTR7OyBnigfpglOvn0WrMfR0Zy9EwxzPfqWQVNyCMdYVtj/4rdjHUD+jPS2nv86ToQ0fyALCBIsXJ6gnEtETrEnZTzZEnWfGb41lIZtcRdIbVak06E7mTgUwojWJeY/0TwVjrBVRpQKQBJDi+qwM2mai5KqZog0+J9waqwBVmrXL4Xo7XdWHgameX4Vznfz7Kh8PLiN4Lhi+6LiAPXQqiH6xY5wcDkBiz/AhGs7YZqK/hy5hgCee04ccWN6wFs7K82IMez7kPLxtvkU1GnNpyTWRqi07xxidG0SvGkVjfIy0TQnpDwTj+tYJczK742DRx4PxvYvsyHbl9P/kd76I4X4wjD/r8oUxAXkYnEE4cyf+8xa1bEXzGVSoRG1ytAWBqoH+4D3A96RsFEjZhYjmKb/48yDNX8aAFGVBUj08YRzO8HIOtwJaU5T0wMM1ueUfUi2ekaIvrFsrHza/lJDCQvUqGR41BVPDf7K51ESniWupZW6o+1V3IrSPdBiurwVRoPpFpwwGc9oMT8MPHaqbyubVmcU3r7X09Hs2ZJYmMCJ46+YHBhNQhcfjw=
  matrix:
  - TMX_DOCKER_IMAGE=ittianhe/tmx-simple-service:chapter1
script:
- docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
- mvn clean package docker:build
- docker push $TMX_DOCKER_IMAGE
- ecs-cli --version
